
CONNECTION_HANDSHAKE = f"josx"
RESP_PACKET_MASK = 0x800
CONTINUE = 0
TRACE = 1
KERNEL_INFO = 2
INT3 = 3
READ_TARGET_MEMORY = 4
WRITE_TARGET_MEMORY = 5
GPF = 6
GET_TASK_LIST = 7
READ_TARGET_MEMORY_RESP = READ_TARGET_MEMORY + RESP_PACKET_MASK
GET_TASK_LIST_RESP = GET_TASK_LIST + RESP_PACKET_MASK

