
CONNECTION_HANDSHAKE = f"josx"
RESP_PACKET_MASK = 0x800
CONTINUE = 0
TRACE = 1
KERNEL_INFO = 2
BREAKPOINT = 3
READ_TARGET_MEMORY = 4
WRITE_TARGET_MEMORY = 5
GPF = 6
GET_TASK_LIST = 7
SINGLE_STEP = 8
TRAVERSE_PAGE_TABLE = 9
ASSERT = 10
READ_MSR = 11

READ_TARGET_MEMORY_RESP = READ_TARGET_MEMORY + RESP_PACKET_MASK
GET_TASK_LIST_RESP = GET_TASK_LIST + RESP_PACKET_MASK
TRAVERSE_PAGE_TABLE_RESP = TRAVERSE_PAGE_TABLE + RESP_PACKET_MASK
READ_MSR_RESP = READ_MSR + RESP_PACKET_MASK



